// 'use strict';
// const dbx = require('../utils/dbx');

// module.exports = {
//   up: function (queryInterface, Sequelize) {
//     return dbx.getLinks()
//     .then(results => {
//       results.entries.forEach((image, idx) => {
//         dogsData[idx].imageLink = image.path_lower;
//       });
//       return queryInterface.bulkInsert('Dogs', dogsData);
//     })
//   },

//   down: function (queryInterface, Sequelize) {
//     /*
//       Add reverting commands here.
//       Return a promise to correctly handle asynchronicity.

//       Example:
//       return queryInterface.bulkDelete('Person', null, {});
//     */
//   }
// };

var dogsDummy = [{
  "name": "Sòng",
  "age": 6,
  "shelter": 6,
  "active": 3,
  "grooming": 2,
  "size": 5,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/1.jpg"
}, {
  "name": "Pénélope",
  "age": 3,
  "shelter": 1,
  "active": 1,
  "grooming": 2,
  "size": 5,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/2.jpg"
}, {
  "name": "Hélèna",
  "age": 6,
  "shelter": 5,
  "active": 2,
  "grooming": 2,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/3.jpg"
}, {
  "name": "Pò",
  "age": 2,
  "shelter": 10,
  "active": 5,
  "grooming": 2,
  "size": 1,
  "noise": 3,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/4.jpg"
}, {
  "name": "Bérengère",
  "age": 2,
  "shelter": 7,
  "active": 1,
  "grooming": 2,
  "size": 4,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/5.jpg"
}, {
  "name": "Fèi",
  "age": 1,
  "shelter": 10,
  "active": 2,
  "grooming": 3,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/6.jpg"
}, {
  "name": "Agnès",
  "age": 5,
  "shelter": 3,
  "active": 4,
  "grooming": 4,
  "size": 1,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/7.jpg"
}, {
  "name": "Célia",
  "age": 3,
  "shelter": 1,
  "active": 4,
  "grooming": 2,
  "size": 5,
  "noise": 1,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/8.jpg"
}, {
  "name": "Crééz",
  "age": 6,
  "shelter": 3,
  "active": 4,
  "grooming": 2,
  "size": 1,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/9.jpg"
}, {
  "name": "Yénora",
  "age": 6,
  "shelter": 5,
  "active": 4,
  "grooming": 3,
  "size": 3,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/10.jpg"
}, {
  "name": "Lyséa",
  "age": 6,
  "shelter": 3,
  "active": 3,
  "grooming": 1,
  "size": 3,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/11.jpg"
}, {
  "name": "Nuó",
  "age": 6,
  "shelter": 4,
  "active": 2,
  "grooming": 4,
  "size": 5,
  "noise": 1,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/12.jpg"
}, {
  "name": "Thérèse",
  "age": 8,
  "shelter": 3,
  "active": 3,
  "grooming": 1,
  "size": 1,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/13.jpg"
}, {
  "name": "Amélie",
  "age": 6,
  "shelter": 10,
  "active": 4,
  "grooming": 3,
  "size": 4,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/14.jpg"
}, {
  "name": "Marie-hélène",
  "age": 1,
  "shelter": 9,
  "active": 1,
  "grooming": 5,
  "size": 3,
  "noise": 1,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/15.jpg"
}, {
  "name": "Kallisté",
  "age": 9,
  "shelter": 4,
  "active": 5,
  "grooming": 2,
  "size": 1,
  "noise": 1,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/16.jpg"
}, {
  "name": "Mà",
  "age": 6,
  "shelter": 3,
  "active": 4,
  "grooming": 2,
  "size": 2,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/17.jpg"
}, {
  "name": "Cléopatre",
  "age": 2,
  "shelter": 2,
  "active": 1,
  "grooming": 2,
  "size": 2,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/18.jpg"
}, {
  "name": "Dà",
  "age": 1,
  "shelter": 2,
  "active": 5,
  "grooming": 2,
  "size": 2,
  "noise": 5,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/19.jpg"
}, {
  "name": "Eléonore",
  "age": 6,
  "shelter": 4,
  "active": 5,
  "grooming": 2,
  "size": 3,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/20.jpg"
}, {
  "name": "Angèle",
  "age": 3,
  "shelter": 5,
  "active": 3,
  "grooming": 1,
  "size": 2,
  "noise": 1,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/21.jpg"
}, {
  "name": "Börje",
  "age": 3,
  "shelter": 4,
  "active": 2,
  "grooming": 3,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/22.jpg"
}, {
  "name": "Maïly",
  "age": 6,
  "shelter": 7,
  "active": 1,
  "grooming": 1,
  "size": 4,
  "noise": 3,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/23.jpg"
}, {
  "name": "Adèle",
  "age": 2,
  "shelter": 8,
  "active": 4,
  "grooming": 3,
  "size": 3,
  "noise": 1,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/24.jpg"
}, {
  "name": "Cléopatre",
  "age": 3,
  "shelter": 5,
  "active": 1,
  "grooming": 2,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/25.jpg"
}, {
  "name": "Méghane",
  "age": 6,
  "shelter": 4,
  "active": 2,
  "grooming": 3,
  "size": 3,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/26.jpg"
}, {
  "name": "Noémie",
  "age": 7,
  "shelter": 1,
  "active": 4,
  "grooming": 4,
  "size": 3,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/27.jpg"
}, {
  "name": "Séréna",
  "age": 3,
  "shelter": 2,
  "active": 2,
  "grooming": 3,
  "size": 3,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/28.jpg"
}, {
  "name": "Marie-josée",
  "age": 11,
  "shelter": 9,
  "active": 2,
  "grooming": 1,
  "size": 5,
  "noise": 3,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/29.jpg"
}, {
  "name": "Nuó",
  "age": 4,
  "shelter": 3,
  "active": 5,
  "grooming": 2,
  "size": 5,
  "noise": 1,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/30.jpg"
}];

module.exports = dogsDummy;