// 'use strict';
// const dbx = require('../utils/dbx');

// module.exports = {
//   up: function (queryInterface, Sequelize) {
//     return dbx.getLinks()
//     .then(results => {
//       results.entries.forEach((image, idx) => {
//         dogsData[idx].imageLink = image.path_lower;
//       });
//       return queryInterface.bulkInsert('Dogs', dogsData);
//     })
//   },

//   down: function (queryInterface, Sequelize) {
//     /*
//       Add reverting commands here.
//       Return a promise to correctly handle asynchronicity.

//       Example:
//       return queryInterface.bulkDelete('Person', null, {});
//     */
//   }
// };

var dogsDummy = [{
  "name": "In-sòck",
  "age": 4,
  "shelter": 6,
  "active": 4,
  "grooming": 2,
  "size": 4,
  "noise": 3,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/1.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Pitbull"
}, {
  "name": "JoshuaBäa",
  "age": 5,
  "shelter": 3,
  "active": 4,
  "grooming": 3,
  "size": 2,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/2.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Pitbull Terrier"
}, {
  "name": "Jòshi",
  "age": 4,
  "shelter": 5,
  "active": 5,
  "grooming": 3,
  "size": 4,
  "noise": 5,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/3.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Husky"
}, {
  "name": "Jason",
  "age": 6,
  "shelter": 8,
  "active": 5,
  "grooming": 5,
  "size": 4,
  "noise": 3,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/4.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Labrador"
}, {
  "name": "JSÖN",
  "age": 2,
  "shelter": 7,
  "active": 4,
  "grooming": 4,
  "size": 3,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/5.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Pitbull"
}, {
  "name": "Insück",
  "age": 3,
  "shelter": 10,
  "active": 4,
  "grooming": 3,
  "size": 3,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/6.jpg",
  "sex": "unisex",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Labrador-mix"
}, {
  "name": "Maāxipadasus",
  "age": 3,
  "shelter": 3,
  "active": 4,
  "grooming": 4,
  "size": 3,
  "noise": 5,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/7.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Pitbull"
}, {
  "name": "MichealHrdLemonade",
  "age": 6,
  "shelter": 5,
  "active": 4,
  "grooming": 2,
  "size": 2,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/8.jpg",
  "sex": "unisex",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Pitbull"
}, {
  "name": "Max-Min",
  "age": 4,
  "shelter": 7,
  "active": 5,
  "grooming": 3,
  "size": 2,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/9.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "pitbull"
}, {
  "name": "Micháel-a",
  "age": 6,
  "shelter": 5,
  "active": 2,
  "grooming": 5,
  "size": 5,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/10.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed": "Afghan Hound"
}, {
  "name": "Jonny-Boy",
  "age": 3,
  "shelter": 3,
  "active": 5,
  "grooming": 4,
  "size": 2,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "	https://s3-us-west-1.amazonaws.com/mutt-match-jason/11.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Airedale"
}, {
  "name": "Jóna-thin",
  "age": 4,
  "shelter": 4,
  "active": 5,
  "grooming": 4,
  "size": 3,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/12.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Akita"
}, {
  "name": "Kay's Jewellers",
  "age": 9,
  "shelter": 3,
  "active": 5,
  "grooming": 5,
  "size": 4,
  "noise": 5,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/13.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Alaskan Malamute"
}, {
  "name": "Ô-Kay",
  "age": 6,
  "shelter": 10,
  "active": 2,
  "grooming": 3,
  "size": 2,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/14.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": false,
  "breed" : "American Bulldog"
}, {
  "name": "Will-I-Am",
  "age": 1,
  "shelter": 5,
  "active": 4,
  "grooming": 3,
  "size": 2,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/15.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Bull-Terrier"
}, {
  "name": "Williámma",
  "age": 9,
  "shelter": 4,
  "active": 5,
  "grooming": 5,
  "size": 2,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/16.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "American Eskimo Dog"
}, {
  "name": "Luwis-van-Feethoven",
  "age": 6,
  "shelter": 3,
  "active": 4,
  "grooming": 2,
  "size": 2,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/17.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Boston-Terrier"
}, {
  "name": "Lewéiner",
  "age": 5,
  "shelter": 2,
  "active": 5,
  "grooming": 2,
  "size": 3,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/18.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Labrador-Pitbull"
}, {
  "name": "Shóe",
  "age": 8,
  "shelter": 2,
  "active": 5,
  "grooming": 3,
  "size": 2,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/19.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Australian Cattle Dog"
}, {
  "name": "Shololol",
  "age": 2,
  "shelter": 4,
  "active": 4,
  "grooming": 3,
  "size": 1,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/20.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Beagle-Mix"
}, {
  "name": "Check-Nâte",
  "age": 3,
  "shelter": 5,
  "active": 2,
  "grooming": 5,
  "size": 2,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/21.jpg",
  "sex": "female",
  "aloneFriendly": true,
  "weatherFriendly": false,
  "breed" : "Bulldog-Mix"
}, {
  "name": "Ivana-Natę",
  "age": 6,
  "shelter": 4,
  "active": 5,
  "grooming": 5,
  "size": 3,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/22.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Boxer-Mix"
}, {
  "name": "Coward Hhen",
  "age": 6,
  "shelter": 7,
  "active": 5,
  "grooming": 3,
  "size": 3,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/23.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Border Collie"

}, {
  "name": "Wård-a-Ho",
  "age": 1,
  "shelter": 8,
  "active": 4,
  "grooming": 3,
  "size": 1,
  "noise": 1,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/24.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Border Terrier"
}, {
  "name": "J?",
  "age": 1,
  "shelter": 5,
  "active": 4,
  "grooming": 3,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/25.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Cairn"
}, {
  "name": "Jay's Son",
  "age": 5,
  "shelter": 4,
  "active": 2,
  "grooming": 2,
  "size": 1,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/26.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Chihuahua-Mix"
}, {
  "name": "Adewhãle",
  "age": 4,
  "shelter": 7,
  "active": 1,
  "grooming": 1,
  "size": 4,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/27.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Chow Chow"
}, {
  "name": "Kevin?",
  "age": 3,
  "shelter": 2,
  "active": 4,
  "grooming": 1,
  "size": 4,
  "noise": 1,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match/images/28.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Rhodesian Ridgeback"
}, {
  "name": "Alex-is Texas",
  "age": 4,
  "shelter": 9,
  "active": 2,
  "grooming": 4,
  "size": 2,
  "noise": 3,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/29.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Affenpinscher"
}, {
  "name": "Ricky-nd-Morty",
  "age": 1,
  "shelter": 3,
  "active": 3,
  "grooming": 3,
  "size": 1,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/30.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Dachshund-Mix"
}, {
  "name": "Kan-t Do it",
  "age": 2,
  "shelter": 8,
  "active": 3,
  "grooming": 2,
  "size": 2,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/31.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Cocker Spaniel"
}, {
  "name": "Hugoes There",
  "age": 6,
  "shelter": 11,
  "active": 4,
  "grooming": 5,
  "size": 2,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/32.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Corgi"
}, {
  "name": "Mariano 'no?ok:' Okpalefe",
  "age": 1,
  "shelter": 9,
  "active": 2,
  "grooming": 2,
  "size": 1,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/33.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Maltese"
}, {
  "name": "Alexandre 'The Great' Kim",
  "age": 3,
  "shelter": 5,
  "active": 5,
  "grooming": 3,
  "size": 2,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/34.jpg",
  "sex": "female",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Jack Russell"
}, {
  "name": "Lewis BraceyFace",
  "age": 2,
  "shelter": 7,
  "active": 5,
  "grooming": 5,
  "size": 5,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/35.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Great Dane"
}, {
  "name": "Michaela Cheng",
  "age": 1,
  "shelter": 10,
  "active": 5,
  "grooming": 5,
  "size": 4,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/36.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "German Shepherd"
}, {
  "name": "Nathan 'extretes' Dunn",
  "age": 1,
  "shelter": 11,
  "active": 5,
  "grooming": 5,
  "size": 3,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/37.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Golden Retriever"
}, {
  "name": "Jonathan Pee",
  "age": 1,
  "shelter": 8,
  "active": 4,
  "grooming": 4,
  "size": 3,
  "noise": 4,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/38.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Rottweiler"
}, {
  "name": "Leather Dirrey",
  "age": 1,
  "shelter": 2,
  "active": 3,
  "grooming": 5,
  "size": 2,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/39.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": false,
  "breed" : "Pug-Mix"
}, {
  "name": "Haimei Mendoza",
  "age": 6,
  "shelter": 8,
  "active": 2,
  "grooming": 4,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/40.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Pomeranian"
}, {
  "name": "Just-in Kang",
  "age": 6,
  "shelter": 11,
  "active": 3,
  "grooming": 1,
  "size": 4,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/41.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Poodle"
}, {
  "name": "Ken Agucci",
  "age": 1,
  "shelter": 4,
  "active": 3,
  "grooming": 1,
  "size": 4,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/42.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Miniature Pinscher"
}, {
  "name": "Mix Scoffman",
  "age": 200,
  "shelter": 7,
  "active": 5,
  "grooming": 1,
  "size": 1,
  "noise": 3,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/43.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Yorkshire Terrier"
}, {
  "name": "Zach 'Bronze' Carr",
  "age": 2,
  "shelter": 9,
  "active": 3,
  "grooming": 3,
  "size": 5,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/44.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Mastiff"
}, {
  "name": "Yuriy 'really' Lemberg",
  "age": 1,
  "shelter": 6,
  "active": 5,
  "grooming": 5,
  "size": 3,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/45.jpg",
  "sex": "female",
  "aloneFriendly": true,
  "weatherFriendly": true,
  "breed" : "Dalmatian-Mix"
}, {
  "name": "William 'Big' Wang",
  "age": 5,
  "shelter": 2,
  "active": 5,
  "grooming": 5,
  "size": 4,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/46.jpg",
  "sex": "female",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Weimaraner"
}, {
  "name": "Sho 'MoFo' Nguyen",
  "age": 3,
  "shelter": 3,
  "active": 2,
  "grooming": 1,
  "size": 1,
  "noise": 2,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/47.jpg",
  "sex": "male",
  "aloneFriendly": true,
  "weatherFriendly": false,
  "breed" : "Shih Tzu-Mix"
}, {
  "name": "Regina 'Serious' Lee",
  "age": 9,
  "shelter": 11,
  "active": 2,
  "grooming": 5,
  "size": 3,
  "noise": 5,
  "experienceReq": false,
  "childFriendly": false,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/48.jpg",
  "sex": "female",
  "aloneFriendly": true,
  "weatherFriendly": false,
  "breed" : "Shar-Pei Mix"
}, {
  "name": "Hugo Dominatrix",
  "age": 3,
  "shelter": 9,
  "active": 4,
  "grooming": 2,
  "size": 3,
  "noise": 2,
  "experienceReq": true,
  "childFriendly": true,
  "dogFriendly": true,
  "petFriendly": true,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/49.jpg",
  "sex": "male",
  "aloneFriendly": false,
  "weatherFriendly": true,
  "breed" : "Schnauzer"
}, {
  "name": "Joshua 'Inside' Bahrs",
  "age": 12,
  "shelter": 7,
  "active": 3,
  "grooming": 2,
  "size": 1,
  "noise": 4,
  "experienceReq": false,
  "childFriendly": true,
  "dogFriendly": false,
  "petFriendly": false,
  "imageLink": "https://s3-us-west-1.amazonaws.com/mutt-match-jason/50.jpg",
  "sex": "female",
  "aloneFriendly": true,
  "weatherFriendly": false,
  "breed" : "Silky Terrier-Mix"
}];

module.exports = dogsDummy;